name: Another different name
description: Blockchain Data for testing purposes.
node_identifier: anyblock-api
platforms:
  - Docker
  - AWS Lambda
  - GCP Functions
data_sources:
  - name: Trying changing this
    url: https://anyblockanalytics.com
parameters:
  - query
  - id
