name: New one name
description: Blockchain for life.
node_identifier: anyblock-api
platforms:
  - Docker
  - AWS Lambda
  - GCP Functions
data_sources:
  - name: Test this change
    url: https://anyblockanalytics.com
parameters:
  - query
  - id
